### PR TITLE
PHP TestFest 2017 at PHPNW17 Conference - New tests for SPL DLL - Manually Iterate with Key

### PR DESCRIPTION
**Pull request by MarkBaker**
Tests for key() method with DLLs when iterating manually

### CODE REVIEW

**Review by krakjoe — APPROVED** [review]

**Comment by carusogabriel** [comment]
We already have a test for that upstream https://github.com/php/php-src/blob/master/ext/spl/tests/SplDoublyLinkedList_key.phpt.

**Comment by coudenysj** [comment]
It really is a shame that the effort in these pull requests is wasted to pull requests that were created in upstream on a later date.

**Comment by carusogabriel** [comment]
@coudenysj From now on, I'll be watching this repository to avoid this.

**Comment by ramsey** [comment]
Sorry, @coudenysj :-(

**Comment by petk** [comment]
Let not the closed pull requests be a demotivation for contributors to open new pull requests directly upstream on the php-src repository in the future. Yes, it really is not good that now we close many pull requests here and not merge them all in, but there really is no other way with some pull requests in the current state of the php-src branches. I fully understand the pain in some pull requests. I would think twice before opening future pull requests myself in such situations but the quality of the PHP software is also very important to everyone - from the core developers to end users who need fully working PHP release. So we need to fine tune:
- quality of the PHP
- merging as much pull requests as possible into the php-src
- keep and working on the restoration of the contributors' faith in the future

Slightly difficult task, but with proper mood from everyone we'll make it.

Cheers.

**Pull request closed without merging**
