### PR TITLE
Added test for php_ini_scanned_files

### PR DESCRIPTION
**Pull request by dwhobbs**

### CODE REVIEW

**Comment by dwhobbs** [comment]
This was done at Madison PHP phptestfest

**Review by krakjoe — CHANGES_REQUESTED** [review]
You cannot rely on compile time configuration dependant behaviour in tests: CI may use a recipe for their build that is entirely different to mine ... my builds will always have scan dir set and will always fail this test ...

Possible solution is a skipif section that runs the test based on the precondition that PHP_INI_SCAN_DIR is not set ...

**Comment by dwhobbs** [comment]
Hi Joe,


Thank you for reviewing this and I appreciate the feedback as I am a fairly new PHP developer, I will look into this as I didn't realize that was the case regarding scan dir in your build.


Thank you,

Derek

________________________________

**Comment by petk** [comment]
Thank you for the pull request. Since we can't know the status of this pr anymore, I'll be merging the rest of the contributions in a single commit... More info on this soon.

**Pull request closed without merging**
