### PR TITLE
Tests for readline()

### PR DESCRIPTION
**Pull request by JonathanStevens**

### CODE REVIEW

**Comment by krakjoe** [comment]
There are quite a few pull requests open for readline, can you please check you are not duplicating tests ?

**Review by carusogabriel — CHANGES_REQUESTED** [review]
Please drop the `ext/readline/tests/readline_with_input.phpt` and let's merge the `ext/readline/tests/readline_without_input.phpt` as we don't have tests covering no input :+1:

**Comment by petk** [comment]
Merge of `ext/readline/tests/readline_without_input.phpt` coming up then... Thanks for the review 👍

**Comment by petk** [comment]
Applied via https://github.com/php/php-src/commit/e94d98e2887fee2dcfc37294a882df107d5ce3ee to the php-src PHP-7.4 and master branches. Thank you @JonathanStevens for the pull request 🎉

**Pull request closed without merging**
