### PR TITLE
Added basic success test for xml_get_error_code

### PR DESCRIPTION
**Pull request by mbniebergall**
Added basic success test for xml_get_error_code.

http://gcov.php.net/PHP_7_2/lcov_html/ext/xml/xml.c.gcov.php for line 1467

Credit: PHP TestFest 2017 - UPHPU

### CODE REVIEW

**Review by krakjoe — CHANGES_REQUESTED** [review]
The description in the test and commit message do not appear to match the intention of the test ... the intention of the test is to specifically test tag mismatch error reporting, or so it would seem ...

**Comment by mbniebergall** [comment]
@krakjoe the intent truly is to test that xml_get_error_code returns the integer error code value as stored in parser->parser->errNo. There are hundreds of possible error codes, as seen here http://www.xmlsoft.org/html/libxml-xmlerror.html#xmlParserErrors . There currently are no tests that validate the the function call returns any error code.

I can add on a few more error codes if that would be helpful to further validate the intent.

**Comment by krakjoe** [comment]
I see, it looks then like you are trying to cover the currently uncovered line:

` 1467           0 :         RETURN_LONG((zend_long)XML_GetErrorCode(parser->parser));`

Can I suggest something like:

```
<?php
$xmlParser = xml_parser_create();
$isSuccess = xml_parse($xmlParser, "
<data>
	<hello/>
</data>
", true);
var_dump(xml_get_error_code($xmlParser) == XML_ERROR_NONE);
?>
```

Looks more like a test for success, and should cover that same line ?

**Comment by mbniebergall** [comment]
@krakjoe good suggestion, I changed the xml and the test to check for XML_ERROR_NONE when the xml is valid.

**Comment by carusogabriel** [comment]
We already have tests for that upstream.

**Pull request closed without merging**
