### PR TITLE
Add test to function posix_getlogin()

### PR DESCRIPTION
**Pull request by royopa**
Increased the coverage lines 587-595 in file ext/posix/posix.c

User Groups: PHPVale    PHPSP    PHPDF   PHPWomenBR

Hangout presented by #PHPTestFestBrasil on 2017-11-14
https://www.youtube.com/watch?v=bBWkzZEadNo

### CODE REVIEW

**Review by krakjoe — APPROVED** [review]

**Comment by krakjoe** [comment]
I'm not sure how to label this ...

**Comment by rogeriopradoj** [comment]
@krakjoe if possible, would be great if this test would be labeled with all UG/Communities that had work on it:

- UG: PHP DF
- UG: PHP SP
- UG: PHPVale
- UG: PHPWomenBR

Even during online editions made under umbrella of this new community #PHPTestFestBrasil (that groups several Brazilian PHP User Group members), we try to add names of each UG.

**Comment by ramsey** [comment]
I've added all these groups as labels. I'm not sure how that will work out in the end, but we'll try it and see. :smile:

**Comment by petk** [comment]
Applied via https://github.com/php/php-src/commit/c2eb68aafedd8a4743a77a0a90680a8a4595a9e1 to PHP-7.4 and master branches. Thank you for your help. 🎉

**Pull request closed without merging**
