### PR TITLE
Add test case for pcntl_setpriority basic behaviour

### PR DESCRIPTION
**Pull request by galvao**
Adding a test case for pcntl_setpriority basic behaviour assuming the user has superuser permission

### CODE REVIEW

**Review by krakjoe — CHANGES_REQUESTED** [review]
We can't have tests that assume supercow powers by default ...

I'm not sure about this, but maybe you could find a way to skipif ... maybe dig about in other tests to see if any other test is doing the same sort of thing ...

Additionally, this function may not always be available when pcntl is loaded, requires skipif on function exists ...

**Comment by galvao** [comment]
@krakjoe Skipif for function_exists is there.
About the superuser issue I see what you mean, I'm going to do some digging to see what I can find.

**Comment by galvao** [comment]
Fixed. Testing for $_SERVER['SUDO_USER'] was the best solution I could find.

**Review by carusogabriel — APPROVED** [review]
This covers http://gcov.php.net/PHP_HEAD/lcov_html/ext/pcntl/pcntl.c.gcov.php#1313

**Comment by petk** [comment]
Applied via https://github.com/php/php-src/commit/eadfdb96178902f8f46bb6a7673f83863f6beac0 to the php-src repository master and PHP-7.4 branches. Thank you @galvao for the pull request 🎉

**Pull request closed without merging**
