### PR TITLE
PHP TestFest 2017 at PHPNW17 Conference - New tests for Closures

### PR DESCRIPTION
**Pull request by MarkBaker**
Test to verify that closures can't be instantiated

### CODE REVIEW

**Comment by ericpoe** [comment]
[non-breaking] `--EXPECTF--` implies that what follows contains variables ala `printf` (like `%s` or `%d`). I think you would want `--EXPECT--` instead.

See: https://qa.php.net/phpt_details.php#expectf_section

**Comment by MarkBaker** [comment]
My bad; I'd originally just tested for the thrown error, so used EXPECTF to handle the filename linenumber in the output; then changed it to add the catches, and forgot to change it to EXPECT... updated it now

**Review by krakjoe — APPROVED** [review]

**Review by carusogabriel — APPROVED** [review]
This covers http://gcov.php.net/PHP_HEAD/lcov_html/Zend/zend_closures.c.gcov.php :clap:

**Comment by petk** [comment]
Applied via https://github.com/php/php-src/commit/c5f9855283733131b9900818e7bc6e997668ffdc into php-src PHP-7.4 and master branches. Thank you @MarkBaker for the pull request and @krakjoe @carusogabriel @ericpoe for the review.

**Pull request closed without merging**
