### PR TITLE
Added basic success test for stream_get_filters

### PR DESCRIPTION
**Pull request by globtec**
Added basic success test for stream_get_filters function

### CODE REVIEW

**Review by krakjoe — APPROVED** [review]

**Review by carusogabriel — COMMENTED** [review]
Looks like this function is already been tested http://gcov.php.net/PHP_HEAD/lcov_html/ext/standard/user_filters.c.gcov.php.

**Comment by carusogabriel** [comment]
Closing as we already have tests for that upstream.

**Comment by petk** [comment]
Hello, this one shows here as not tested yet:
http://gcov.php.net/viewer.php?version=PHP_HEAD&func=tested_functions

Also, I'm not sure there are *.phpt files containing tests for `stream_get_filters()` specifically.

**Comment by petk** [comment]
cc @carusogabriel when you have some time, do you maybe have any explanation please why the gcov doesn't have this marked as tested? Should we recheck this one? Thank you...

**Comment by carusogabriel** [comment]
@petk I don't remember why, but the "Tested Functions" page isn't trustable. The "Coverage" one is.

**Comment by petk** [comment]
Ok, thanks for the info... What about that these aren't even anywhere in the *.phpt files in the --FILE-- sections? For example, from my quick search, the only 3 occurrences in tests are:
* ext/standard/tests/filters/chunked_001.phpt
* ext/standard/tests/filters/stream_filter_remove_basic.phpt
* ext/standard/tests/filters/stream_filter_remove_error.phpt

in the --SKIPIF-- section. Is that fine?

**Pull request closed without merging**
