### PR TITLE
Add test for pcntl_getpriority() basic behaviour

### PR DESCRIPTION
**Pull request by galvao**
Adding test for pcntl_getpriority() basic behaviour (passing no parameters).

### CODE REVIEW

**Review by krakjoe — CHANGES_REQUESTED** [review]
This function may not be defined even when pcntl is loaded, please add a skipif on function_exists.

The expect doesn't seem to be correct, the function returns long, I'm not sure what %s:%d is for, please review that again.

**Comment by galvao** [comment]
Fixed. Thanks!

**Review by carusogabriel — APPROVED** [review]
There's no single test for the `pcntl_getpriority` function.

**Comment by petk** [comment]
Applied via https://github.com/php/php-src/commit/d22dd5f93a687ed208ca39e451ae5ab7d7dc6be3 into php-src PHP-7.4 and master branches. Thank you @galvao for the pull request and @krakjoe @carusogabriel for the review.

**Pull request closed without merging**
