### PR TITLE
PHP TestFest 2017- phpdublin -  Bug #75421: Invalid values accepted for the SoapHeader actor parameter.

### PR DESCRIPTION
**Pull request by kenguest**
As per the spec,the SoapHeader actor attribute/parameter should be an URI/URL.

https://www.w3.org/TR/2000/NOTE-SOAP-20000508/#_Toc478383499

There is no validation to ensure this is the case, this test fails intentionally to demonstrate the issue.

### CODE REVIEW

**Comment by krakjoe** [comment]
Tests expected to fail should use an XFAIL section, so they don't break CI ...

**Review by krakjoe — CHANGES_REQUESTED** [review]
XFAIL

**Comment by kenguest** [comment]
@krakjoe I've added in that XFAIL section now...

**Comment by petk** [comment]
Thank you for the pull request. Since we can't know the status of this pr anymore, I'll be merging the rest of the contributions in a single commit... More info on this soon.

**Pull request closed without merging**
