### PR TITLE
corrected typo in test

### PR DESCRIPTION
**Pull request by royopa**
User Group: PHPSP #phptestfestbrasil

### CODE REVIEW

**Review by krakjoe — APPROVED** [review]

**Review by carusogabriel — APPROVED** [review]
I'll be merging this one into https://github.com/php/php-src as it is a trivial change :+1:

**Comment by petk** [comment]
Hello, merged via https://github.com/php/php-src/commit/dc1937e386082dddbcab612889ad8cb15df88b73 into the php-src repository.

@ramsey how do you suggest to handle the merged pull requests in this repository? Should they be closed and marked as merged in the [spreadsheet](https://docs.google.com/spreadsheets/u/1/d/17lnjueQx2LouoIopPnzUK5Q2p3SdqnPcv3_ykQ9rIBU/edit?usp=sharing)?

**Comment by ramsey** [comment]
@petk That sounds like a great idea. @ericpoe, I think you're the owner of the spreadsheet. Can you grant me and Peter access to edit it? Peter, I'm granting you access to close PRs in this repo. Who else needs access to help with this effort?

**Comment by ramsey** [comment]
I also granted access to @carusogabriel.

**Comment by petk** [comment]
Thank you @ramsey for the info. Then I'll be closing this one as successfully merged.

**Comment by carusogabriel** [comment]
@ramsey Thank you. I'll be reviewing the PRs, closing those ones that are not valid/duplicated/etc and approving those ones that @petk will be merging into `php-src`. Thank you for your support.

**Comment by ramsey** [comment]
Thank you for your help!

**Pull request closed without merging**
