### PR TITLE
Add ZIP add file failure test

### PR DESCRIPTION
**Pull request by wardcapp**
User Group: PHP-WVL & PHPGent #PHPTestFest

### CODE REVIEW

**Comment by coudenysj** [comment]
Are the tests failing because of the changes? Or is there a general problem with the travis ci builds?

**Comment by krakjoe** [comment]
The failure is unrelated.

**Comment by krakjoe** [comment]
I'm not sure why ext/zip is not included in coverage at gcov, possibly because the bundled libzip would skew coverage numbers, not sure ...

I see a couple of tests that appear to have these paths covered, can you check that you are not duplicating code in other tests please ?

**Comment by wardcapp** [comment]
@krakjoe you're right, upon double-checking, the very same path is already covered by (at least) **ext/zip/tests/bug64342_1.phpt**.
I indeed assumed the test was new due to the gcov results.

Thank you for your feedback and sorry about this, will take it into account next time :)

**Pull request closed without merging**
